const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.TiledBg,
		C3.Plugins.Sprite,
		C3.Behaviors.DragnDrop,
		C3.Plugins.Mouse,
		C3.Plugins.progressbar,
		C3.Plugins.Shape3D,
		C3.Plugins.Text,
		C3.Plugins.Button,
		C3.Plugins.Button.Cnds.OnClicked,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.Button.Acts.Destroy,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.Button.Acts.SetVisible,
		C3.Plugins.Button.Acts.SetEnabled,
		C3.Plugins.Sprite.Cnds.IsOverlapping,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.progressbar.Acts.SetProgress,
		C3.Plugins.Mouse.Cnds.OnObjectClicked,
		C3.Plugins.Mouse.Cnds.IsOverObject,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Plugins.Sprite.Acts.SetOpacity
	];
};
self.C3_JsPropNameTable = [
	{Background: 0},
	{DragDrop: 0},
	{RAM: 0},
	{Boitier: 0},
	{ramPort: 0},
	{ConnecteurUSB: 0},
	{SATAoptique: 0},
	{Mouse: 0},
	{alimSSD: 0},
	{ProgressBar: 0},
	{"3DShape": 0},
	{postit: 0},
	{Sprite2: 0},
	{Text: 0},
	{OK: 0},
	{Indice: 0},
	{ButtonIndice: 0},
	{Sprite: 0},
	{Sprite3: 0},
	{Sprite4: 0},
	{fleche: 0},
	{fleche2: 0},
	{fleche3: 0},
	{TaskStep: 0}
];

self.InstanceType = {
	Background: class extends self.ITiledBackgroundInstance {},
	RAM: class extends self.ISpriteInstance {},
	Boitier: class extends self.ISpriteInstance {},
	ramPort: class extends self.ISpriteInstance {},
	ConnecteurUSB: class extends self.ISpriteInstance {},
	SATAoptique: class extends self.ISpriteInstance {},
	Mouse: class extends self.IInstance {},
	alimSSD: class extends self.ISpriteInstance {},
	ProgressBar: class extends self.IProgressBarInstance {},
	_3DShape: class extends self.I3DShapeInstance {},
	postit: class extends self.ISpriteInstance {},
	Sprite2: class extends self.ISpriteInstance {},
	Text: class extends self.ITextInstance {},
	OK: class extends self.IButtonInstance {},
	Indice: class extends self.ITextInstance {},
	ButtonIndice: class extends self.IButtonInstance {},
	Sprite: class extends self.ISpriteInstance {},
	Sprite3: class extends self.ISpriteInstance {},
	Sprite4: class extends self.ISpriteInstance {},
	fleche: class extends self.ISpriteInstance {},
	fleche2: class extends self.ISpriteInstance {},
	fleche3: class extends self.ISpriteInstance {}
}